export const tools = [
  {
    id: "code-image",
    name: "代码画布",
    category: "创作与分享",
    icon: "⌘",
    description: "将代码转为精美图片。实时预览，一键导出 PNG / SVG。",
    tags: ["语法高亮", "图片导出"],
    hint: "本地生成图片，不上传代码。",
    example: "",
  },
  {
    id: "json",
    name: "JSON 格式化",
    category: "数据处理",
    icon: "{ }",
    description: "让复杂数据，清晰有序。格式化、压缩与校验 JSON。",
    tags: ["格式化", "压缩", "校验"],
    hint: "保留大整数精度，重复键会明确报错。",
    example:
      '{"name":"Wind","version":1,"features":["简单","免费","本地处理"],"ready":true}',
  },
  {
    id: "timestamp",
    name: "时间戳转换",
    category: "日期与时间",
    icon: "◷",
    description: "在时间戳与日期之间轻松转换，支持秒和毫秒。",
    tags: ["秒 / 毫秒", "UTC / 本地"],
    hint: "显式选择单位和时区，避免时间偏差。",
    example: "1789344000000",
  },
  {
    id: "jwt",
    name: "JWT 解析",
    category: "数据处理",
    icon: "◇",
    description: "快速查看 Header、Payload 和 Token 时间信息。",
    tags: ["Header", "Payload", "过期检查"],
    hint: "仅解码内容，不验证签名；请勿粘贴敏感 Token。",
    example:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2luZCIsImlhdCI6MTc4OTM0NDAwMCwiZXhwIjoxODkzNDU2MDAwfQ.demo",
  },
  {
    id: "sql",
    name: "SQL 格式化",
    category: "数据库",
    icon: "≡",
    description: "整理查询语句，让每一层逻辑都更容易阅读。",
    tags: ["MySQL", "PostgreSQL", "Oracle"],
    hint: "格式化不代表语法有效或可以执行。首发暂不提供 SQL 压缩。",
    example:
      "select u.id, u.name, count(o.id) as orders from users u left join orders o on u.id = o.user_id where u.active = 1 group by u.id, u.name order by orders desc;",
  },
  {
    id: "diff",
    name: "文本 Diff",
    category: "文本处理",
    icon: "±",
    description: "并排比较两段文本，快速定位新增、删除和未变化的行。",
    tags: ["行级对比", "本地比较"],
    hint: "适合代码、配置、SQL、日志和普通文本；单侧最多 1,200 行。",
    example: "",
  },
  {
    id: "codec",
    name: "Base64 / URL 编解码",
    category: "编码转换",
    icon: "↔",
    description: "在 Base64、URL 编码与原始文本之间快速转换。",
    tags: ["Base64", "URL Encode"],
    hint: "Base64 按 UTF-8 文本处理；URL 使用标准 percent-encoding。",
    example: "Wind DevTools 中文 / hello?x=1&y=2",
  },
  {
    id: "json-type",
    name: "JSON 转类型",
    category: "数据处理",
    icon: "<>",
    description: "根据 JSON 结构生成 TypeScript 接口或 Java 类型。",
    tags: ["TypeScript", "Java"],
    hint: "根据当前样例推断字段类型；复杂数组会按样例中的首个 Java 元素推断。",
    example:
      '{"id":1001,"name":"Wind","active":true,"profile":{"city":"Shanghai"},"tags":["dev","tools"]}',
  },
  {
    id: "text",
    name: "批量文本处理",
    category: "文本处理",
    icon: "¶",
    description: "去重、排序、去空行、Trim、大小写与批量前后缀。",
    tags: ["去重", "排序", "批处理"],
    hint: "按行处理的操作会保留文本顺序语义；大小写转换作用于全文。",
    example: " beta \nalpha\nalpha\n\n gamma ",
  },
  {
    id: "cron",
    name: "Cron 表达式",
    category: "日期与时间",
    icon: "↻",
    description: "生成常用计划，查看字段含义和未来执行时间。",
    tags: ["Linux", "Quartz", "执行时间"],
    hint: "Quartz 支持常用 6 字段；不支持年份和 L、W、#。",
    example: "0 */5 * * * ?",
  },
] as const;
export type ToolId = (typeof tools)[number]["id"];
export const categories = [
  "全部工具",
  "数据处理",
  "日期与时间",
  "数据库",
  "文本处理",
  "编码转换",
  "创作与分享",
];
